DROP DATABASE IF EXISTS EVENT_TICKETING;
CREATE DATABASE EVENT_TICKETING;
USE event_ticketing;
SELECT 'MySQL schema initialization placeholder completed.' AS status;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FNAME VARCHAR(100) NOT NULL,
    USER_LNAME VARCHAR(100) NOT NULL,
    ACCT_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VENUES (
    VENUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VENUE_NAME VARCHAR(100) NOT NULL,
    VENUE_CAPACITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTS (
    EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TITLE VARCHAR(100) NOT NULL,
    EVENT_DATETIME DATETIME NOT NULL,
    VENUE_ID INT NOT NULL,
    TOTAL_SALES DEC(19,4) NOT NULL DEFAULT 0,
    TICKETS_SOLD INT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_EVENTS_VENUES
        FOREIGN KEY (VENUE_ID)
        REFERENCES VENUES(VENUE_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);

-- need these two tables for many-to-many relationship requirement
CREATE TABLE IF NOT EXISTS TICKET_TYPES(
    TICKET_TYPE VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TICKET_TYPE_ASSIGNMENTS (
	EVENT_ID INT NOT NULL,
    TICKET_TYPE VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (
        EVENT_ID,
        TICKET_TYPE
    ),

    CONSTRAINT FK_TICKET_TYPE_ASSIGNMENTS_EVENTS
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(EVENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_TICKET_TYPE_ASSIGNMENTS_TICKET_TYPES
        FOREIGN KEY (TICKET_TYPE)
        REFERENCES TICKET_TYPES(TICKET_TYPE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    INDEX IDX_TICKET_TYPE_ASSIGNMENTS_TICKET_TYPES (
        TICKET_TYPE
    )

);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    BALANCE DEC(19,4) NOT NULL DEFAULT 0,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    ORDER_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_ORDERS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);


CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
	ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    TICKET_PRICE DEC(19,4) NOT NULL,
    
    CONSTRAINT FK_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
        
    CONSTRAINT FK_ORDER_ITEMS_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(EVENT_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE


);


CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PAYMENT_AMT DEC(19,4) NOT NULL CHECK (PAYMENT_AMT > 0),
    
    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);

DELIMITER $$

CREATE TRIGGER TRG_BI_ORDER_ITEMS
BEFORE INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
    DECLARE TICKETS_AVAIL INT;
	SELECT V.VENUE_CAPACITY - E.TICKETS_SOLD INTO TICKETS_AVAIL
    FROM (
        SELECT VENUE_ID, VENUE_CAPACITY FROM VENUES
    ) V JOIN (
        SELECT VENUE_ID, TICKETS_SOLD FROM EVENTS
        WHERE EVENT_ID = NEW.EVENT_ID
    ) E
    ON V.VENUE_ID = E.VENUE_ID;
    IF TICKETS_AVAIL < 1 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "Event Sold Out";
    END IF;
END$$

CREATE TRIGGER TRG_AI_ORDER_ITEMS_ORDERS
AFTER INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
	UPDATE ORDERS
	SET
		BALANCE = BALANCE + NEW.TICKET_PRICE
	WHERE ORDER_ID = NEW.ORDER_ID;
END$$

CREATE TRIGGER TRG_AI_ORDER_ITEMS_EVENTS
AFTER INSERT ON ORDER_ITEMS
FOR EACH ROW
FOLLOWS TRG_AI_ORDER_ITEMS_ORDERS
BEGIN
	UPDATE EVENTS
	SET
		TICKETS_SOLD = TICKETS_SOLD + 1,
		TOTAL_SALES = TOTAL_SALES + NEW.TICKET_PRICE
	WHERE EVENT_ID = NEW.EVENT_ID;
END$$

CREATE TRIGGER TRG_PAYMENTS 
BEFORE INSERT ON PAYMENTS 
FOR EACH ROW
BEGIN
DECLARE OVERPAY VARCHAR(1);
DECLARE BALANCE_ DEC(19,4);
SELECT BALANCE INTO BALANCE_
    FROM ORDERS
    WHERE ORDER_ID = NEW.ORDER_ID;
SET OVERPAY = CASE WHEN BALANCE_ < NEW.PAYMENT_AMT THEN 'Y' ELSE 'N' END;
IF OVERPAY = 'N' THEN
	UPDATE ORDERS
		SET
			BALANCE = BALANCE - NEW.PAYMENT_AMT,
			STATUS = CASE
				WHEN BALANCE = 0 
				THEN 'PAID'
				ELSE STATUS
			END
			WHERE ORDER_ID = NEW.ORDER_ID;
END IF;
END$$


DELIMITER ;
