DROP DATABASE IF EXISTS EVENT_TICKETING;
CREATE DATABASE EVENT_TICKETING;
USE event_ticketing;
SELECT 'MySQL schema initialization placeholder completed.' AS status;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FNAME VARCHAR(100) NOT NULL,
    USER_LNAME VARCHAR(100) NOT NULL,
    ACCT_CREATED DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS VENUES (
    VENUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VENUE_NAME VARCHAR(100) NOT NULL,
    VENUE_CAPACITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTS (
    EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TITLE VARCHAR(100) NOT NULL,
    EVENT_DATETIME DATETIME NOT NULL,
    VENUE_ID INT NOT NULL,
    TOTAL_SALES INT NOT NULL DEFAULT 0,
    TICKETS_SOLD INT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_EVENTS_VENUES
        FOREIGN KEY (VENUE_ID)
        REFERENCES VENUES(VENUE_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);

-- need these two tables for many-to-many relationship requirement
CREATE TABLE IF NOT EXISTS EVENT_CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,

    CONSTRAINT UNIQUE_EVENT_CATEGORIES_NAME
        UNIQUE (CATEGORY_NAME)
);

CREATE TABLE IF NOT EXISTS EVENT_CATEGORY_ASSIGNMENTS (
    EVENT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    
    PRIMARY KEY (
        EVENT_ID,
        CATEGORY_ID
    ),

    CONSTRAINT FK_EVENT_CATEGORY_ASSIGNMENTS_EVENTS
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(EVENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_EVENT_CATEGORY_ASSIGNMENTS_EVENT_CATEGORIES
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES EVENT_CATEGORIES(CATEGORY_ID)
        ON DELETE CASCADE,
    
    INDEX IDX_EVENT_CATEGORY_ASSIGNMENTS_EVENT_CATEGORIES (
        CATEGORY_ID
    )

);

CREATE TABLE IF NOT EXISTS TICKET_TYPES (
    TICKET_TYPE VARCHAR(100) PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    BALANCE INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    
    CONSTRAINT FK_ORDERS_USERS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);


CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
	ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    TICKET_TYPE VARCHAR(100) NOT NULL,
    TICKET_PRICE INT NOT NULL,
    
    CONSTRAINT FK_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
        
    CONSTRAINT FK_ORDER_ITEMS_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(EVENT_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE


);


CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PAYMENT_AMT INT NOT NULL CHECK (PAYMENT_AMT > 0),
    
    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);

DELIMITER $$

CREATE TRIGGER TRG_ORDER_ITEMS
AFTER INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
	UPDATE ORDERS
	SET
		BALANCE = BALANCE + NEW.TICKET_PRICE
	WHERE ORDER_ID = NEW.ORDER_ID;
END$$

CREATE TRIGGER TRG_PAYMENTS
AFTER INSERT ON PAYMENTS
FOR EACH ROW
BEGIN
	UPDATE ORDERS
	SET
		BALANCE = BALANCE - NEW.PAYMENT_AMT,
		STATUS = CASE
			WHEN BALANCE = 0 THEN 'PAID'
			ELSE STATUS
	END
	WHERE ORDER_ID = NEW.ORDER_ID;
END$$

DELIMITER ;
