USE EVENT_TICKETING;

SELECT * FROM orders;

START TRANSACTION;
INSERT INTO ORDERS(ORDER_ID, USER_ID) VALUES(6, 2);
INSERT INTO ORDER_ITEMS(ORDER_ID, EVENT_ID, TICKET_PRICE) VALUES
(6, 4, 650),
(6, 4, 650),
(6, 4, 650),
(6, 4, 650),
(6, 4, 650);
INSERT INTO PAYMENTS(ORDER_ID, PAYMENT_AMT) VALUES (6, 3.50);
COMMIT;
ROLLBACK;

SELECT * FROM ORDERS;